@startuml

title 状態遷移図

'画面遷移'
[*] -left-> プロフィール設定画面 : ゲーム初回起動時のみ
[*] -down-> タイトル画面

プロフィール設定画面 -down-> タイトル画面

タイトル画面 -down-> マルチプレイ画面 : 遊ぶ
タイトル画面 -left-> オプション画面 : オプション
タイトル画面 -right-> [*] : 終了

オプション画面 -right-> タイトル画面 : 戻る
オプション画面 -left-> 成績画面 : 成績

成績画面 -right-> オプション画面 : 戻る

マルチプレイ画面 -left-> 部屋作成画面 : 部屋を作る
マルチプレイ画面 -right-> 部屋を探す画面 : 部屋を探す
マルチプレイ画面 -up-> タイトル画面 : 戻る
マルチプレイ画面 -down->フィールド選択画面 : 散歩

部屋作成画面 -down-> 参加者待機画面 : 決定
部屋作成画面 -right-> マルチプレイ画面 : 戻る

部屋を探す画面 -down-> 参加者待機画面 : 部屋選択
部屋を探す画面 -left-> マルチプレイ画面 : 戻る

参加者待機画面 -down-> メイン画面 : 全員参加状態\nホストのみが\n遷移決定権を\n持つ
参加者待機画面 -down-> フィールド選択画面 : ホストのみが\n遷移決定権を\n持つ
参加者待機画面 -up-> 部屋作成画面 : 戻る\n(部屋作成画面から\n遷移時のみ)
参加者待機画面 -up-> 部屋を探す画面 : 戻る\n(部屋を探すから\n遷移時のみ)

フィールド選択画面 -up-> 参加者待機画面 : 戻る\n(参加者待機\n画面から\n遷移時のみ)
フィールド選択画面 -up-> マルチプレイ画面 : 戻る\n(散歩で\n遷移時のみ)
フィールド選択画面 -left->メイン画面 : 決定

メイン画面 -up-> リザルト画面 : ゲーム終了\n(参加者待機画面から\n遷移時のみ)
メイン画面 -right->フィールド選択画面 : 戻る\n(散歩で遷移時のみ)

リザルト画面 -right-> 参加者待機画面 : もう一度プレイする
リザルト画面 -left-> タイトル画面 : タイトルに戻る


'各画面定義'
プロフィール設定画面 : 名前入力

タイトル画面 : タイトルロゴ
タイトル画面 : 遊ぶ
タイトル画面 : オプション
タイトル画面 : 終了

オプション画面 : 名前の変更
オプション画面 : コントローラの設定
オプション画面 : 成績
オプション画面 : 戻る

成績画面 : 成績表示
成績画面 : 戻る

マルチプレイ画面 : 部屋を作る
マルチプレイ画面 : 部屋を探す
マルチプレイ画面 : 散歩
マルチプレイ画面 : 戻る

部屋作成画面 : 部屋名
部屋作成画面 : 人数
部屋作成画面 : オプション
部屋作成画面 : パスワード設定
部屋作成画面 : 人で参加
部屋作成画面 : 鬼で参加
部屋作成画面 : 決定
部屋作成画面 : 戻る

部屋を探す画面 : 公開部屋一覧
部屋を探す画面 : 部屋名入力
部屋を探す画面 : パスワード入力
部屋を探す画面 : 一覧更新
部屋を探す画面 : 人で参加
部屋を探す画面 : 鬼で参加
部屋を探す画面 : 戻る

フィールド選択画面 : 決定
フィールド選択画面 : ランダム
フィールド選択画面 : 戻る

参加者待機画面 : メンバーが集まるまで待つ
参加者待機画面 : 鬼種類変更
参加者待機画面 : 人装備変更
参加者待機画面 : 人武器変更
参加者待機画面 : 戻る
参加者待機画面 : スタート

メイン画面 : 鬼が勝つか人が勝つまで続ける
メイン画面 : 戻る(散歩時のみ)

リザルト画面 : 結果を表示する
リザルト画面 : もう一度プレイする
リザルト画面 : タイトルに戻る

@enduml
