@startuml

title クラス図

'privateやpublicのアイコンをやめて-や+で記載'
skinparam classAttributeIconSize 0

'定義----------------------------------------------------------------------------------------------------'
namespace Kamitsuki {

    namespace Models {

        namespace Configs {

            'ConfigModel------------------------------------------'
            ConfigModel : + string UserName
            ConfigModel : + DateTime FirstLoginDate
            '--------------------------------------------------------'
            ConfigModel : + ConfigModel()
            '--------------------------------------------------------'

        }

    }

    namespace Presenters {

        namespace Title {

            'TitlePresenter------------------------------------------'
            TitlePresenter : - TitleBackView TitleBackView
            TitlePresenter : - TitleLogoView TitleLogoView
            TitlePresenter : - TitleSelectorView TitleSelectorView
            '--------------------------------------------------------'
            TitlePresenter : + void Initialized()
            '--------------------------------------------------------'

        }

        namespace Option {

            'ProfileSetterPresenter------------------------------------------'
            ProfileSetterPresenter : - ConfigModel ConfigModel
            ProfileSetterPresenter : - ProfileSetterView ProfileSetterView
            '--------------------------------------------------------'
            ProfileSetterPresenter : + void Initialized()
            '--------------------------------------------------------'

        }

        namespace Score {

            'ScorePresenter------------------------------------------'
            ScorePresenter : - ConfigModel ConfigModel
            ScorePresenter : - ScoreView ScoreView
            '--------------------------------------------------------'
            ScorePresenter : + void Initialized()
            '--------------------------------------------------------'

        }

        namespace MultiPlay {

            namespace Entrance {
            }

            namespace Lobby {

                namespace RoomCreater {
                }

                namespace RoomSearcher {
                }

                namespace StandbyRoom {
                }

                namespace HumanCustomizer {
                }

                namespace OgreCustomizer {
                }

                namespace FieldSelecter {
                }

            }

            namespace MainGame {
            }

        }

        namespace Result {
        }

    }

    namespace Views {

        namespace Title {

            'TitleBackView------------------------------------------'
            '--------------------------------------------------------'
            TitleBackView : + void Initialized()
            TitleBackView : + void Update()
            '--------------------------------------------------------'

            'TitleLogoView------------------------------------------'
            TitleLogoView : + Action OnAnyUserOperationListener
            TitleLogoView : + Action OnEndAnimationListener
            '--------------------------------------------------------'
            TitleLogoView : + void Initialized()
            TitleLogoView : + void Update()
            TitleLogoView : + void OnAnyUserOperation()
            TitleLogoView : + void ForceFinishAnimation()
            '--------------------------------------------------------'

            'TitleSelectorView---------------------------------------'
            TitleSelectorView : + Action OnClickedPlayListener
            TitleSelectorView : + Action OnClickedOptionListener
            TitleSelectorView : + Action OnClickedExitListener
            '--------------------------------------------------------'
            TitleSelectorView : + void Initialized()
            TitleSelectorView : + void ForceShowSelector()
            TitleSelectorView : + void OnClickedPlay()
            TitleSelectorView : + void OnClickedOption()
            TitleSelectorView : + void OnClickedExit()
            '--------------------------------------------------------'

        }

        namespace Option {

            'OptionView------------------------------------------'
            OptionView : + Action OnClickedChangeProfileListener
            OptionView : + Action OnClickedSettingControllerListener
            OptionView : + Action OnClickedResultListener
            OptionView : + Action OnClickedBackListener
            '--------------------------------------------------------'
            OptionView : + void OnClickedChangeProfile()
            OptionView : + void OnClickedSettingController()
            OptionView : + void OnClickedResult()
            OptionView : + void OnClickedBack()
            '--------------------------------------------------------'

            'ProfileSetterView------------------------------------------'
            ProfileSetterView : + Action OnClickedDesitionListener
            ProfileSetterView : + Action OnClickedCancelListener
            ProfileSetterView : + Action OnEndClosingAnimationListener
            '--------------------------------------------------------'
            ProfileSetterView : + void Initialized()
            ProfileSetterView : + void OnClickedDesision()
            ProfileSetterView : + void OnClickedCancel()
            ProfileSetterView : + void CloseWindow()
            '--------------------------------------------------------'

        }

        namespace Score {

            'ScoreView------------------------------------------'
            ScoreView : + Action OnClickedBackListener
            '--------------------------------------------------------'
            ScoreView : + void Initialized()
            ScoreView : + void OnClickedBack()
            '--------------------------------------------------------'

        }

        namespace MultiPlay {

            namespace Entrance {

                'EntranceView------------------------------------------'
                EntranceView : + Action OnClickedCreateRoomListener
                EntranceView : + Action OnClickedSearchRoomListener
                EntranceView : + Action OnClickedFieldWalkListener
                EntranceView : + Action OnClickedBackListener
                '--------------------------------------------------------'
                EntranceView : + void OnClickedCreateRoom()
                EntranceView : + void OnClickedSearchRoom()
                EntranceView : + void OnClickedFieldWalk()
                EntranceView : + void OnClickedBack()
                '--------------------------------------------------------'

            }

            namespace Lobby {

                namespace RoomCreater {

                    'RoomCreaterView------------------------------------------'
                    RoomCreaterView : + Action OnClickedCreateRoomListener
                    RoomCreaterView : + Action OnClickedSetDetailListener
                    RoomCreaterView : + Action OnClickedBackListener
                    '--------------------------------------------------------'
                    RoomCreaterView : + void OnClickedCreateRoom()
                    RoomCreaterView : + void OnClickedSetDetail()
                    RoomCreaterView : + void OnClickedBack()
                    '--------------------------------------------------------'

                    'RoomDetailSetterView------------------------------------------'
                    RoomDetailSetterView : + Action OnClickedBackListener
                    '--------------------------------------------------------'
                    RoomDetailSetterView : + void OnClickedBack()
                    '--------------------------------------------------------'

                }

                namespace RoomSearcher {

                    'RoomSearcherView------------------------------------------'
                    RoomSearcherView : + Action OnUpdateListListener
                    RoomSearcherView : + Action OnSelectedRoomListener
                    RoomSearcherView : + Action OnClickedBackListener
                    '--------------------------------------------------------'
                    RoomSearcherView : + void OnUpdateList()
                    RoomSearcherView : + void OnSelectedRoom()
                    RoomSearcherView : + void OnClickedBack()
                    '--------------------------------------------------------'

                    'AppointeeView------------------------------------------'
                    AppointeeView : + Action OnUpdateListListener
                    AppointeeView : + Action OnSelectedRoomListener
                    AppointeeView : + Action OnClickedBackListener
                    '--------------------------------------------------------'
                    AppointeeView : + void OnUpdateList()
                    AppointeeView : + void OnSelectedRoom()
                    AppointeeView : + void OnClickedBack()
                    '--------------------------------------------------------'

                }

                namespace StandbyRoom {

                    'StandbyRoomView------------------------------------------'
                    StandbyRoomView : + Action OnClickedStartListener
                    StandbyRoomView : + Action OnClickedBackListener
                    '--------------------------------------------------------'
                    StandbyRoomView : + void OnClickedStart()
                    StandbyRoomView : + void OnClickedBack()
                    '--------------------------------------------------------'

                }

                namespace OgreCustomizer {

                    'OgreCustomizerView------------------------------------------'
                    OgreCustomizerView : + Action OnClickedBackListener
                    '--------------------------------------------------------'
                    OgreCustomizerView : + void OnClickedBack()
                    '--------------------------------------------------------'

                }

                namespace HumanCustomizer {

                    'EquipCustomizerView------------------------------------------'
                    EquipCustomizerView : + Action OnClickedBackListener
                    '--------------------------------------------------------'
                    EquipCustomizerView : + void OnClickedBack()
                    '--------------------------------------------------------'

                    'WeaponCustomizerView------------------------------------------'
                    WeaponCustomizerView : + Action OnClickedBackListener
                    '--------------------------------------------------------'
                    WeaponCustomizerView : + void OnClickedBack()
                    '--------------------------------------------------------'

                }

                namespace FieldSelecter {

                    'FieldSelecterView------------------------------------------'
                    FieldSelecterView : + Action OnClickedBackListener
                    '--------------------------------------------------------'
                    FieldSelecterView : + void OnClickedBack()
                    '--------------------------------------------------------'

                }

            }

            namespace MainGame {


            }

        }

        namespace Result {

            'ResultView------------------------------------------'
            ResultView : + Action OnClickedRestartListener
            ResultView : + Action OnClickedBackListener
            '--------------------------------------------------------'
            ResultView : + void OnClickedRestart()
            ResultView : + void OnClickedBack()
            '--------------------------------------------------------'

        }

    }

}

'遷移図----------------------------------------------------------------------------------------------------'

Kamitsuki.Models.Configs.ConfigModel -right-o Kamitsuki.Presenters.Option.ProfileSetterPresenter
Kamitsuki.Presenters.Option.ProfileSetterPresenter o-right- Kamitsuki.Views.Option.ProfileSetterView

Kamitsuki.Presenters.Title.TitlePresenter o-right- Kamitsuki.Views.Title.TitleBackView
Kamitsuki.Presenters.Title.TitlePresenter o-right- Kamitsuki.Views.Title.TitleLogoView
Kamitsuki.Presenters.Title.TitlePresenter o-right- Kamitsuki.Views.Title.TitleSelectorView

Kamitsuki.Models.Configs.ConfigModel -right-o Kamitsuki.Presenters.Score.ScorePresenter
Kamitsuki.Presenters.Score.ScorePresenter -right-o Kamitsuki.Views.Score.ScoreView

'レイアウト補助----------------------------------------------------------------------------------------------------'
Kamitsuki.Models -[hidden]--> Kamitsuki.Presenters
Kamitsuki.Presenters -[hidden]--> Kamitsuki.Views

Kamitsuki.Presenters.Title -[hidden]--> Kamitsuki.Presenters.Option
Kamitsuki.Presenters.Option -[hidden]--> Kamitsuki.Presenters.Score
Kamitsuki.Presenters.Score -[hidden]--> Kamitsuki.Presenters.MultiPlay
Kamitsuki.Presenters.MultiPlay.Entrance -[hidden]--> Kamitsuki.Presenters.MultiPlay.Lobby
Kamitsuki.Presenters.Lobby.RoomCreater -[hidden]--> Kamitsuki.Presenters.Lobby.RoomSearcher
Kamitsuki.Presenters.Lobby.RoomSearcher -[hidden]--> Kamitsuki.Presenters.Lobby.StandbyRoom
Kamitsuki.Presenters.Lobby.StandbyRoom -[hidden]--> Kamitsuki.Presenters.Lobby.HumanCustomizer
Kamitsuki.Presenters.Lobby.HumanCustomizer -[hidden]--> Kamitsuki.Presenters.Lobby.OgreCustomizer
Kamitsuki.Presenters.MultiPlay.Lobby -[hidden]--> Kamitsuki.Presenters.MultiPlay.MainGame
Kamitsuki.Presenters.MultiPlay -[hidden]--> Kamitsuki.Presenters.Result

Kamitsuki.Views.Title -[hidden]--> Kamitsuki.Views.Option
Kamitsuki.Views.Option -[hidden]--> Kamitsuki.Views.Score
Kamitsuki.Views.Score -[hidden]--> Kamitsuki.Views.MultiPlay
Kamitsuki.Views.MultiPlay.Entrance -[hidden]--> Kamitsuki.Views.MultiPlay.Lobby
Kamitsuki.Views.Lobby.RoomCreater -[hidden]--> Kamitsuki.Views.Lobby.RoomSearcher
Kamitsuki.Views.Lobby.RoomSearcher -[hidden]--> Kamitsuki.Views.Lobby.StandbyRoom
Kamitsuki.Views.Lobby.StandbyRoom -[hidden]--> Kamitsuki.Views.Lobby.HumanCustomizer
Kamitsuki.Views.Lobby.HumanCustomizer -[hidden]--> Kamitsuki.Views.Lobby.OgreCustomizer
Kamitsuki.Views.MultiPlay.Lobby -[hidden]--> Kamitsuki.Views.MultiPlay.MainGame
Kamitsuki.Views.MultiPlay -[hidden]--> Kamitsuki.Views.Result

@enduml