@startuml

title クラス図

'privateやpublicのアイコンをやめて-や+で記載'
skinparam classAttributeIconSize 0

'定義'
namespace Kamitsuki {

    namespace Models {

    }

    namespace Presenters {

        namespace Title {
        }

        namespace Option {
        }

        namespace CharacterSelect {
        }

        namespace HumanCustomizer {
        }

        namespace OgreCustomizer {
        }

        namespace MultiPlay {

            namespace Entrance {
            }

            namespace Lobby {
            }

            namespace MainGame {
            }

        }

        namespace Result {
        }

    }

    namespace Views {

        namespace Title {

            'TitleBackView------------------------------------------'
            TitleBackView : + void Update()
            '--------------------------------------------------------'

            'TitleLogoView------------------------------------------'
            TitleLogoView : + Action OnAnyUserOperationListener
            TitleLogoView : + Action OnEndAnimationListener
            '--------------------------------------------------------'
            TitleLogoView : + void Update()
            TitleLogoView : + void OnAnyUserOperation()
            '--------------------------------------------------------'

            'TitleSelectorView------------------------------------------'
            TitleSelectorView : + Action OnClickedPlayListener
            TitleSelectorView : + Action OnClickedOptionListener
            TitleSelectorView : + Action OnClickedExitListener
            '--------------------------------------------------------'
            TitleSelectorView : + void OnClickedPlay()
            TitleSelectorView : + void OnClickedOption()
            TitleSelectorView : + void OnClickedExit()
            '--------------------------------------------------------'

        }

        namespace Option {

            'OptionView------------------------------------------'
            OptionView : + Action OnClickedChangeProfileListener
            OptionView : + Action OnClickedSettingControllerListener
            OptionView : + Action OnClickedResultListener
            OptionView : + Action OnClickedBackListener
            '--------------------------------------------------------'
            OptionView : + void OnClickedChangeProfile()
            OptionView : + void OnClickedSettingController()
            OptionView : + void OnClickedResult()
            OptionView : + void OnClickedBack()
            '--------------------------------------------------------'

        }

        namespace Score {

            'ScoreView------------------------------------------'
            ScoreView : + Action OnClickedBackListener
            '--------------------------------------------------------'
            ScoreView : + void OnClickedBack()
            '--------------------------------------------------------'

        }

        namespace MultiPlay {

            namespace Entrance {

                'EntranceView------------------------------------------'
                EntranceView : + Action OnClickedCreateRoomListener
                EntranceView : + Action OnClickedSearchRoomListener
                EntranceView : + Action OnClickedFieldWalkListener
                EntranceView : + Action OnClickedBackListener
                '--------------------------------------------------------'
                EntranceView : + void OnClickedCreateRoom()
                EntranceView : + void OnClickedSearchRoom()
                EntranceView : + void OnClickedFieldWalk()
                EntranceView : + void OnClickedBack()
                '--------------------------------------------------------'

            }

            namespace Lobby {

                namespace RoomCreater {

                    'RoomCreaterView------------------------------------------'
                    RoomCreaterView : + Action OnClickedCreateRoomListener
                    RoomCreaterView : + Action OnClickedSetDetailListener
                    RoomCreaterView : + Action OnClickedBackListener
                    '--------------------------------------------------------'
                    RoomCreaterView : + void OnClickedCreateRoom()
                    RoomCreaterView : + void OnClickedSetDetail()
                    RoomCreaterView : + void OnClickedBack()
                    '--------------------------------------------------------'

                    'RoomDetailSetterView------------------------------------------'
                    RoomDetailSetterView : + Action OnClickedBackListener
                    '--------------------------------------------------------'
                    RoomDetailSetterView : + void OnClickedBack()
                    '--------------------------------------------------------'

                }

                namespace RoomSearcher {

                    'RoomSearcherView------------------------------------------'
                    RoomSearcherView : + Action OnUpdateListListener
                    RoomSearcherView : + Action OnSelectedRoomListener
                    RoomSearcherView : + Action OnClickedBackListener
                    '--------------------------------------------------------'
                    RoomSearcherView : + void OnUpdateList()
                    RoomSearcherView : + void OnSelectedRoom()
                    RoomSearcherView : + void OnClickedBack()
                    '--------------------------------------------------------'

                    'AppointeeView------------------------------------------'
                    AppointeeView : + Action OnUpdateListListener
                    AppointeeView : + Action OnSelectedRoomListener
                    AppointeeView : + Action OnClickedBackListener
                    '--------------------------------------------------------'
                    AppointeeView : + void OnUpdateList()
                    AppointeeView : + void OnSelectedRoom()
                    AppointeeView : + void OnClickedBack()
                    '--------------------------------------------------------'

                }

                namespace StandbyRoom {

                    'StandbyRoomView------------------------------------------'
                    StandbyRoomView : + Action OnClickedStartListener
                    StandbyRoomView : + Action OnClickedBackListener
                    '--------------------------------------------------------'
                    StandbyRoomView : + void OnClickedStart()
                    StandbyRoomView : + void OnClickedBack()
                    '--------------------------------------------------------'

                }

                namespace OgreCustomizer {

                    'OgreCustomizerView------------------------------------------'
                    OgreCustomizerView : + Action OnClickedBackListener
                    '--------------------------------------------------------'
                    OgreCustomizerView : + void OnClickedBack()
                    '--------------------------------------------------------'

                }

                namespace HumanCustomizer {

                    'EquipCustomizerView------------------------------------------'
                    EquipCustomizerView : + Action OnClickedBackListener
                    '--------------------------------------------------------'
                    EquipCustomizerView : + void OnClickedBack()
                    '--------------------------------------------------------'

                    'WeaponCustomizerView------------------------------------------'
                    WeaponCustomizerView : + Action OnClickedBackListener
                    '--------------------------------------------------------'
                    WeaponCustomizerView : + void OnClickedBack()
                    '--------------------------------------------------------'

                }

                namespace FieldSelecter {

                    'FieldSelecterView------------------------------------------'
                    FieldSelecterView : + Action OnClickedBackListener
                    '--------------------------------------------------------'
                    FieldSelecterView : + void OnClickedBack()
                    '--------------------------------------------------------'

                }

            }

            namespace MainGame {


            }

        }

        namespace Result {

            'ResultView------------------------------------------'
            ResultView : + Action OnClickedRestartListener
            ResultView : + Action OnClickedBackListener
            '--------------------------------------------------------'
            ResultView : + void OnClickedRestart()
            ResultView : + void OnClickedBack()
            '--------------------------------------------------------'

        }

    }

}

'遷移図'

@enduml